// Generated by CoffeeScript 1.7.1
(function() {
  var clipboard, io, open, program, request, server;

  io = require('socket.io-client');

  request = require('request');

  open = require('open');

  clipboard = require('copy-paste');

  program = require('commander');

  program.option('-l, --local', 'Local').parse(process.argv);

  server = program.local ? 'http://localhost:3000/' : 'http://webcatio.herokuapp.com:80/';

  request.post(server, function(err, res, body) {
    var id, socket, target;
    if (err) {
      console.log(err);
    }
    console.log('made request!');
    console.log('body = ' + body);
    id = body;
    target = server + id;
    clipboard.copy(target);
    socket = io.connect(target);
    open(target);
    return socket.on('connect', function() {
      process.stdin.setEncoding('utf8');
      return process.stdin.on('readable', function() {
        var data;
        data = process.stdin.read();
        return socket.emit('data', data);
      });
    });
  });

}).call(this);
