// Generated by CoffeeScript 1.7.1
(function() {
  var clipboard, convert, converter, io, open, processData, program, request, savedStdin, server, util;

  io = require('socket.io-client');

  request = require('request');

  open = require('open');

  clipboard = require('copy-paste');

  util = require('util');

  convert = require('ansi-to-html');

  converter = new convert();

  savedStdin = "";

  process.stdin.on('data', function(data) {
    return savedStdin += data;
  });

  program = require('commander');

  program.option('-l, --local', 'Local').parse(process.argv);

  server = program.local ? 'http://localhost:3000/' : 'http://webcatio.herokuapp.com:80/';

  request.post(server, function(err, res, body) {
    var id, socket, target, targetForOutput;
    id = body;
    target = server + id;
    targetForOutput = target.replace(":80", "");
    clipboard.copy(target);
    socket = io.connect(target);
    open(target);
    return socket.on('connect', function() {
      process.stdin.setEncoding('utf8');
      console.log("STREAM " + id);
      console.log("To view stream, visit " + targetForOutput);
      console.log("This link is also copied to the clipboard");
      setTimeout(function() {
        return socket.emit('data', processData(savedStdin));
      }, 1000);
      process.stdin.on('data', function(data) {
        if (data) {
          data = processData(data);
        }
        return socket.emit('data', data);
      });
      return process.on('SIGINT', function() {
        console.log('\nexiting...');
        socket.emit('exit', '');
        return process.exit(2);
      });
    });
  });

  processData = function(data) {
    data = data.split(" ").join("&nbsp;").split("\n").join("<br />");
    data = converter.toHtml(data);
    return data;
  };

}).call(this);
