// Generated by CoffeeScript 1.7.1
(function() {
  var clipboard, convert, converter, io, open, program, request, savedStdin, server, util;

  io = require('socket.io-client');

  request = require('request');

  open = require('open');

  clipboard = require('copy-paste');

  util = require('util');

  convert = require('ansi-to-html');

  converter = new convert();

  savedStdin = "";

  process.stdin.on('data', function(data) {
    return savedStdin += data;
  });

  program = require('commander');

  program.option('-l, --local', 'Local').parse(process.argv);

  server = program.local ? 'http://localhost:3000/' : 'http://webcatio.herokuapp.com:80/';

  request.post(server, function(err, res, body) {
    var id, socket, target;
    id = body;
    target = server + id;
    clipboard.copy(target);
    socket = io.connect(target);
    open(target);
    return socket.on('connect', function() {
      process.stdin.setEncoding('utf8');
      process.stdin.resume();
      setTimeout(function() {
        return socket.emit('data', savedStdin);
      }, 1000);
      process.stdin.on('data', function(data) {
        if (data) {
          data = converter.toHtml(data);
          data = data;
        }
        return socket.emit('data', data);
      });
      return process.on('SIGINT', function() {
        console.log('\nexiting...');
        socket.emit('exit', '');
        return process.exit(2);
      });
    });
  });

}).call(this);
